---
services:
    mongodb:
        image: mongo:7.0.25
        restart: unless-stopped
        ports:
            - "127.0.0.1:27017:27017"
        volumes:
            - cozy_data_dev:/data/db

volumes:
    cozy_data_dev:
